server:
  port: 80



# 配置zipkin链路追踪
#原理：web的方式，把每个请求的数据发给链路追踪服务器 zipkin，
spring:
  zipkin:
    base-url: http://192.168.200.100:9411
    sender:
      type: web
#      gateway实现同意跨域的配置

  cloud:
    gateway:



##前端页面地址：
#         - id: web_all_route
#          uri: lb://web-all
#          predicate:
#            - Path=/admin/product/**

      globalcors:
        cors-configurations:
          '[/**]':
#            同意所有的地址来源
            allowedOrigins: "*"
#            同意所有请求
            allowedMethods: "*"
            allowedHeaders: "*" # 同意复制跨域请求头中携带
            allowCredentials: true #同意带一些安全标志跨域：比如cookie
      routes:
        - id: product_route
          uri: lb://service-product
          predicates:
            - Path=/admin/product/**
        - id: cart_router
          uri: lb://service-cart
          predicates:
            - Path=/api/cart/**
         # 登录页面的路由配置
        - id: user_route
          uri: lb://service-user
          predicates:
            - Path=/api/user/**


        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com
##          登录页面的异步地址
#        - id: user_route
#         - uri: lb://service-user
#           predicates:
#             - Path=/api/user/**

## 配置 过滤器过滤请求配置配置
#app:
#  auth:
#    no-auth-url:   #任何无须登录访问的页面
#      - /css/**
#      - /js/**
#      - /img/**
#
#    login-auth-url: #登录同意后才能访问的资源
#      -  /order/**
#
#    loginPage: http://passport.gamll.com/login.html
app:
  auth:
    no-auth-url:
      # 任何人都能访问的路径
      - /css/**
      - /js/**
      - /img/**
      - /login.html
      - /api/user/passport/login

    login-auth-url:
      # 登录后才能访问的资源
      -  /order/**

    # 重新重定向去的路径
    login-page: http://passport.gmall.com/login.html

    # 拒绝通过浏览器访问的地址
    deny-url:
      - /api/inner/**




