server:
  port: 80



# 配置zipkin链路追踪
#原理：web的方式，把每个请求的数据发给链路追踪服务器 zipkin，
spring:
  zipkin:
    base-url: http://192.168.200.100:9411
    sender:
      type: web
#      gateway实现同意跨域的配置

  cloud:

    gateway:
      routes:
        - id: product_route
          uri: lb://service-product  #lb 负载均衡的意思
          predicates: #断言
            - Path=/admin/product/**

    #前端页面地址：
        - id: web_all_route
          uri: lb://web-all
          predicates:
            - Host=**.gmall.com


      globalcors:
        cors-configurations:
          '[/**]':
#            同意所有的地址来源
            allowedOrigins: "*"
#            同意所有请求
            allowedMethods: "*"
            allowedHeaders: "*" # 同意复制跨域请求头中携带
            allowCredentials: true #同意带一些安全标志跨域：比如cookie




